nseeds: 3

sim_dir: input
#########simulation parameters ################
clones:
  - 5
  # - 9



coverage:
  - 0.05
  - 0.1
  - 0.25


cells:
  - 1000




mutations:
  - 15000


#num of each time of CNA events to include
cna_chrom: 4
cna_arm: 8
cna_bin: 0

num_cna:
  '5': 3
  '9': 5


max_add_copies: 4
loss:
  - 0
  # - 2
  
# loh:
#   - "l0_loh0"
  # - "l2_loh2"
# cnloh_cna_loss:
#   # - - 2
#   #   - 2
#   - - 0
#     - 0

fp: 
 - 0.001

#proportion of snvs that are lost from the root node: higher =more lost SNVs
loss_rate: 0.5

#controls the min number of "both" cna and snv nodes 
cna: 3

# min_snv_nodes: 3

#dirichlet distributions parameter alpha
dp_clones:
  - 2

dp_snv:
  - 2

dp_cnv:
  - 2



#minimum threshold or dirichlet distributioms
cp_thresh: 0.05
vaf_thresh: 0.05


#phertilizer params
max_copies: 9
# radius: 0.975
radius: 1
fp: 0.001
mode: "rd"
starts: 16
max_iterations: 50
min_obs: 5

low_cmb: 0.05
high_cmb: 0.15
nobs_per_cluster: 3
