
simpath: "../clonesim/build/simulate"
genpath: "../clonesim/build/generatesinglecells"
nseeds: 5

cells:
  - 500
  - 1000
  # - 5000

snvs:
  - 1000
  - 5000
  - 10000
# - 25000

cov:
  - 0.01
  - 0.05
  # - 0.1
  - 0.25
  - 1

cerror:
  - 0
  # - 0.15

nsegs:
  - 25
  # - 50
  # - 100

mclust:
  - 5
  - 7







